//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMS.Models
{
    
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    
    /// <summary>
    /// MisArticle
    /// </summary>
    public partial class MisArticle:EntityBase
    {
        /// <summary>
        /// 
        /// </summary>
    	[Display(Name="")][Key]
        public string Id { get; set; }
    	   
        
        /// <summary>
        /// 
        /// </summary>
    	[Display(Name="")]
        public int ChannelId { get; set; }
    	   
        
        /// <summary>
        /// 
        /// </summary>
    	[Display(Name="")]
        public string CategoryId { get; set; }
    	   
        
        /// <summary>
        /// 
        /// </summary>
    	[Display(Name="")]
        public string Title { get; set; }
    	   
        
        /// <summary>
        /// 
        /// </summary>
    	[Display(Name="")]
        public string ImgUrl { get; set; }
    	   
        
        /// <summary>
        /// 
        /// </summary>
    	[Display(Name="")]
        public string BodyContent { get; set; }
    	   
        
        /// <summary>
        /// 
        /// </summary>
    	[Display(Name="")]
        public Nullable<int> Sort { get; set; }
    	   
        
        /// <summary>
        /// 
        /// </summary>
    	[Display(Name="")]
        public Nullable<int> Click { get; set; }
    	   
        
        /// <summary>
        /// 
        /// </summary>
    	[Display(Name="")]
        public int CheckFlag { get; set; }
    	   
        
        /// <summary>
        /// 
        /// </summary>
    	[Display(Name="")]
        public string Checker { get; set; }
    	   
        
        /// <summary>
        /// 
        /// </summary>
    	[Display(Name="")]
        public Nullable<System.DateTime> CheckDateTime { get; set; }
    	   
        
        /// <summary>
        /// 
        /// </summary>
    	[Display(Name="")]
        public string Creater { get; set; }
    	   
        
        /// <summary>
        /// 
        /// </summary>
    	[Display(Name="")]
        public Nullable<System.DateTime> CreateTime { get; set; }
    	   
        
    }
}
