// This file was automatically generated by the T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `ConnectionString`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=.;Initial Catalog=UMSDB;User ID=sa;Password=******;Connect Timeout=30`
//     Include Views:          `False`

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;
using UMS.Utility;

namespace UMS.Models
{
    /// <summary>
    /// A class which represents the SysLoginInfo table.
    /// </summary>
	[Table("SysLoginInfo")]
	public partial class SysLoginInfo:EntityBase<int>
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual DateTime CreateTime { get; set; }
		public virtual Guid LoginToken { get; set; }
		public virtual DateTime LastAccessTime { get; set; }
		public virtual int SysUserId { get; set; }
		public virtual string LoginName { get; set; }
		public virtual string BusinessPermissionString { get; set; }
		public virtual string ClientIP { get; set; }
		public virtual int EnumLoginAccountType { get; set; }
	}

    /// <summary>
    /// A class which represents the SysModule table.
    /// </summary>
	[Table("SysModule")]
	public partial class SysModule:EntityBase<int>
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual string EnglishName { get; set; }
		public virtual int? ParentId { get; set; }
		public virtual string Url { get; set; }
		public virtual string Iconic { get; set; }
		public virtual int? Sort { get; set; }
		public virtual string Remark { get; set; }
		public virtual bool? State { get; set; }
		public virtual string CreatePerson { get; set; }
		public virtual DateTime? CreateTime { get; set; }
		public virtual bool IsLast { get; set; }
		public virtual byte[] Version { get; set; }
		public virtual SysModule SysModuleEntity { get; set; }
		public virtual IEnumerable<SysModule> SysModules { get; set; }
		public virtual IEnumerable<SysModuleOperate> SysModuleOperates { get; set; }
		public virtual IEnumerable<SysRight> SysRights { get; set; }
	}

    /// <summary>
    /// A class which represents the SysModuleOperate table.
    /// </summary>
	[Table("SysModuleOperate")]
	public partial class SysModuleOperate:EntityBase<int>
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual string KeyCode { get; set; }
		public virtual int ModuleId { get; set; }
		public virtual bool IsValid { get; set; }
		public virtual int Sort { get; set; }
		public virtual SysModule SysModuleEntity { get; set; }
	}

    /// <summary>
    /// A class which represents the SysRightOperate table.
    /// </summary>
	[Table("SysRightOperate")]
	public partial class SysRightOperate:EntityBase<int>
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual int RightId { get; set; }
		public virtual string KeyCode { get; set; }
		public virtual bool IsValid { get; set; }
		public virtual SysRight SysRightEntity { get; set; }
	}

    /// <summary>
    /// A class which represents the SysRole table.
    /// </summary>
	[Table("SysRole")]
	public partial class SysRole:EntityBase<int>
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual string Description { get; set; }
		public virtual DateTime CreateTime { get; set; }
		public virtual string CreatePerson { get; set; }
		public virtual IEnumerable<SysRight> SysRights { get; set; }
		public virtual IEnumerable<SysUserRole> SysUserRoles { get; set; }
	}

    /// <summary>
    /// A class which represents the SysRight table.
    /// </summary>
	[Table("SysRight")]
	public partial class SysRight:EntityBase<int>
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual int ModuleId { get; set; }
		public virtual int RoleId { get; set; }
		public virtual bool Rightflag { get; set; }
		public virtual SysModule SysModuleEntity { get; set; }
		public virtual SysRole SysRoleEntity { get; set; }
		public virtual IEnumerable<SysRightOperate> SysRightOperates { get; set; }
	}

    /// <summary>
    /// A class which represents the SysUser table.
    /// </summary>
	[Table("SysUser")]
	public partial class SysUser:EntityBase<int>
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string UserName { get; set; }
		public virtual string Password { get; set; }
		public virtual string TrueName { get; set; }
		public virtual string Cards { get; set; }
		public virtual string MobileNumber { get; set; }
		public virtual string PhoneNumber { get; set; }
		public virtual string QQ { get; set; }
		public virtual string EmailAddress { get; set; }
		public virtual string OtherContact { get; set; }
		public virtual string Province { get; set; }
		public virtual string City { get; set; }
		public virtual string Village { get; set; }
		public virtual string Address { get; set; }
		public virtual bool? State { get; set; }
		public virtual DateTime? CreateTime { get; set; }
		public virtual string CreatePerson { get; set; }
		public virtual string Sex { get; set; }
		public virtual DateTime? Birthday { get; set; }
		public virtual DateTime? JoinDate { get; set; }
		public virtual string Marital { get; set; }
		public virtual string Political { get; set; }
		public virtual string Nationality { get; set; }
		public virtual string Native { get; set; }
		public virtual string School { get; set; }
		public virtual string Professional { get; set; }
		public virtual string Degree { get; set; }
		public virtual string DepId { get; set; }
		public virtual string PosId { get; set; }
		public virtual string Expertise { get; set; }
		public virtual string JobState { get; set; }
		public virtual string Photo { get; set; }
		public virtual string Attach { get; set; }
		public virtual IEnumerable<SysUserRole> SysUserRoles { get; set; }
	}

    /// <summary>
    /// A class which represents the SysUserRole table.
    /// </summary>
	[Table("SysUserRole")]
	public partial class SysUserRole:EntityBase<int>
	{
		[Key]
		[Column(Order=0)]
    	public virtual int SysUserId { get; set; }
		[Key]
		[Column(Order=1)]
    	public virtual int SysRoleId { get; set; }
		public virtual SysUser SysUserEntity { get; set; }
		public virtual SysRole SysRoleEntity { get; set; }
	}

}
