//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMS.Models
{
    
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    
    /// <summary>
    /// SysLoginInfo
    /// </summary>
    public partial class SysLoginInfo:EntityBase
    {
        /// <summary>
        /// 
        /// </summary>
    	[Display(Name="")][Key]
        public int Id { get; set; }
    	   
        
        /// <summary>
        /// 
        /// </summary>
    	[Display(Name="")]
        public System.DateTime CreateTime { get; set; }
    	   
        
        /// <summary>
        /// 
        /// </summary>
    	[Display(Name="")]
        public System.Guid LoginToken { get; set; }
    	   
        
        /// <summary>
        /// 
        /// </summary>
    	[Display(Name="")]
        public System.DateTime LastAccessTime { get; set; }
    	   
        
        /// <summary>
        /// 
        /// </summary>
    	[Display(Name="")]
        public string SysUserId { get; set; }
    	   
        
        /// <summary>
        /// 
        /// </summary>
    	[Display(Name="")]
        public string LoginName { get; set; }
    	   
        
        /// <summary>
        /// 
        /// </summary>
    	[Display(Name="")]
        public string BusinessPermissionString { get; set; }
    	   
        
        /// <summary>
        /// 
        /// </summary>
    	[Display(Name="")]
        public string ClientIP { get; set; }
    	   
        
        /// <summary>
        /// 
        /// </summary>
    	[Display(Name="")]
        public int EnumLoginAccountType { get; set; }
    	   
        
    }
}
