//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMS.Models
{
    
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    
    /// <summary>
    /// SysLoginInfo
    /// </summary>
    public partial class SysLoginInfo:EntityBase
    {
        /// <summary>
        /// Id
        /// </summary>
    	[Display(Name="Id")][Key]
        public int Id { get; set; }
    	   
        
        /// <summary>
        /// CreateTime
        /// </summary>
    	[Display(Name="CreateTime")]
        public System.DateTime CreateTime { get; set; }
    	   
        
        /// <summary>
        /// LoginToken
        /// </summary>
    	[Display(Name="LoginToken")]
        public System.Guid LoginToken { get; set; }
    	   
        
        /// <summary>
        /// LastAccessTime
        /// </summary>
    	[Display(Name="LastAccessTime")]
        public System.DateTime LastAccessTime { get; set; }
    	   
        
        /// <summary>
        /// SysUserId
        /// </summary>
    	[Display(Name="SysUserId")]
        public string SysUserId { get; set; }
    	   
        
        /// <summary>
        /// LoginName
        /// </summary>
    	[Display(Name="LoginName")]
        public string LoginName { get; set; }
    	   
        
        /// <summary>
        /// BusinessPermissionString
        /// </summary>
    	[Display(Name="BusinessPermissionString")]
        public string BusinessPermissionString { get; set; }
    	   
        
        /// <summary>
        /// ClientIP
        /// </summary>
    	[Display(Name="ClientIP")]
        public string ClientIP { get; set; }
    	   
        
        /// <summary>
        /// EnumLoginAccountType
        /// </summary>
    	[Display(Name="EnumLoginAccountType")]
        public int EnumLoginAccountType { get; set; }
    	   
        
    }
}
