//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMS.Models
{
    
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    
    /// <summary>
    /// SysLog
    /// </summary>
    public partial class SysLog:EntityBase
    {
        /// <summary>
        /// Id
        /// </summary>
    	[Display(Name="Id")][Key]
        public System.Guid Id { get; set; }
    	   
        
        /// <summary>
        /// Category
        /// </summary>
    	[Display(Name="Category")]
        public string Category { get; set; }
    	   
        
        /// <summary>
        /// ErrorUrl
        /// </summary>
    	[Display(Name="ErrorUrl")]
        public string ErrorUrl { get; set; }
    	   
        
        /// <summary>
        /// Message
        /// </summary>
    	[Display(Name="Message")]
        public string Message { get; set; }
    	   
        
        /// <summary>
        /// Exception
        /// </summary>
    	[Display(Name="Exception")]
        public string Exception { get; set; }
    	   
        
        /// <summary>
        /// Method
        /// </summary>
    	[Display(Name="Method")]
        public string Method { get; set; }
    	   
        
        /// <summary>
        /// Line
        /// </summary>
    	[Display(Name="Line")]
        public string Line { get; set; }
    	   
        
        /// <summary>
        /// Params
        /// </summary>
    	[Display(Name="Params")]
        public string Params { get; set; }
    	   
        
        /// <summary>
        /// CreateTime
        /// </summary>
    	[Display(Name="CreateTime")]
        public Nullable<System.DateTime> CreateTime { get; set; }
    	   
        
    }
}
