//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMS.Models
{
    
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    
    /// <summary>
    /// SysLog
    /// </summary>
    public partial class SysLog:EntityBase
    {
        /// <summary>
        /// 
        /// </summary>
    	[Display(Name="")][Key]
        public System.Guid Id { get; set; }
    	   
        
        /// <summary>
        /// 
        /// </summary>
    	[Display(Name="")]
        public string Category { get; set; }
    	   
        
        /// <summary>
        /// 
        /// </summary>
    	[Display(Name="")]
        public string ErrorUrl { get; set; }
    	   
        
        /// <summary>
        /// 
        /// </summary>
    	[Display(Name="")]
        public string Message { get; set; }
    	   
        
        /// <summary>
        /// 
        /// </summary>
    	[Display(Name="")]
        public string Exception { get; set; }
    	   
        
        /// <summary>
        /// 
        /// </summary>
    	[Display(Name="")]
        public string Method { get; set; }
    	   
        
        /// <summary>
        /// 
        /// </summary>
    	[Display(Name="")]
        public string Line { get; set; }
    	   
        
        /// <summary>
        /// 
        /// </summary>
    	[Display(Name="")]
        public string Params { get; set; }
    	   
        
        /// <summary>
        /// 
        /// </summary>
    	[Display(Name="")]
        public Nullable<System.DateTime> CreateTime { get; set; }
    	   
        
    }
}
