//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMS.Models
{
    
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    
    /// <summary>
    /// SysModule
    /// </summary>
    public partial class SysModule:EntityBase
    {
        /// <summary>
        /// 编码
        /// </summary>
    	[Display(Name="编码")][Key]
        public string Id { get; set; }
    	   
        
        /// <summary>
        /// 名称
        /// </summary>
    	[Display(Name="名称")]
        public string Name { get; set; }
    	   
        
        /// <summary>
        /// 英文名称
        /// </summary>
    	[Display(Name="英文名称")]
        public string EnglishName { get; set; }
    	   
        
        /// <summary>
        /// 上级编码
        /// </summary>
    	[Display(Name="上级编码")]
        public string ParentId { get; set; }
    	   
        
        /// <summary>
        /// 路径
        /// </summary>
    	[Display(Name="路径")]
        public string Url { get; set; }
    	   
        
        /// <summary>
        /// 图标
        /// </summary>
    	[Display(Name="图标")]
        public string Iconic { get; set; }
    	   
        
        /// <summary>
        /// 排序
        /// </summary>
    	[Display(Name="排序")]
        public Nullable<int> Sort { get; set; }
    	   
        
        /// <summary>
        /// 备注
        /// </summary>
    	[Display(Name="备注")]
        public string Remark { get; set; }
    	   
        
        /// <summary>
        /// 启用
        /// </summary>
    	[Display(Name="启用")]
        public bool Enable { get; set; }
    	   
        
        /// <summary>
        /// 创建人
        /// </summary>
    	[Display(Name="创建人")]
        public string CreateUser { get; set; }
    	   
        
        /// <summary>
        /// 创建时间
        /// </summary>
    	[Display(Name="创建时间")]
        public Nullable<System.DateTime> CreateTime { get; set; }
    	   
        
        /// <summary>
        /// 
        /// </summary>
    	[Display(Name="")]
        public bool IsLast { get; set; }
    	   
        
    }
}
