//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMS.Models
{
    
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    
    /// <summary>
    /// SysModule
    /// </summary>
    public partial class SysModule:EntityBase
    {
        /// <summary>
        /// Id
        /// </summary>
    	[Display(Name="Id")][Key]
        public string Id { get; set; }
    	   
        
        /// <summary>
        /// Name
        /// </summary>
    	[Display(Name="Name")]
        public string Name { get; set; }
    	   
        
        /// <summary>
        /// EnglishName
        /// </summary>
    	[Display(Name="EnglishName")]
        public string EnglishName { get; set; }
    	   
        
        /// <summary>
        /// ParentId
        /// </summary>
    	[Display(Name="ParentId")]
        public string ParentId { get; set; }
    	   
        
        /// <summary>
        /// Url
        /// </summary>
    	[Display(Name="Url")]
        public string Url { get; set; }
    	   
        
        /// <summary>
        /// Iconic
        /// </summary>
    	[Display(Name="Iconic")]
        public string Iconic { get; set; }
    	   
        
        /// <summary>
        /// Sort
        /// </summary>
    	[Display(Name="Sort")]
        public Nullable<int> Sort { get; set; }
    	   
        
        /// <summary>
        /// Remark
        /// </summary>
    	[Display(Name="Remark")]
        public string Remark { get; set; }
    	   
        
        /// <summary>
        /// Enable
        /// </summary>
    	[Display(Name="Enable")]
        public bool Enable { get; set; }
    	   
        
        /// <summary>
        /// CreateUser
        /// </summary>
    	[Display(Name="CreateUser")]
        public string CreateUser { get; set; }
    	   
        
        /// <summary>
        /// CreateTime
        /// </summary>
    	[Display(Name="CreateTime")]
        public Nullable<System.DateTime> CreateTime { get; set; }
    	   
        
        /// <summary>
        /// IsLast
        /// </summary>
    	[Display(Name="IsLast")]
        public bool IsLast { get; set; }
    	   
        
    }
}
