//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMS.Models
{
    
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    
    /// <summary>
    /// SysModuleOperate
    /// </summary>
    public partial class SysModuleOperate:EntityBase
    {
        /// <summary>
        /// Id
        /// </summary>
    	[Display(Name="Id")][Key]
        public string Id { get; set; }
    	   
        
        /// <summary>
        /// Name
        /// </summary>
    	[Display(Name="Name")]
        public string Name { get; set; }
    	   
        
        /// <summary>
        /// KeyCode
        /// </summary>
    	[Display(Name="KeyCode")]
        public string KeyCode { get; set; }
    	   
        
        /// <summary>
        /// ModuleId
        /// </summary>
    	[Display(Name="ModuleId")]
        public string ModuleId { get; set; }
    	   
        
        /// <summary>
        /// IsValid
        /// </summary>
    	[Display(Name="IsValid")]
        public bool IsValid { get; set; }
    	   
        
        /// <summary>
        /// Sort
        /// </summary>
    	[Display(Name="Sort")]
        public int Sort { get; set; }
    	   
        
    }
}
