//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMS.Models
{
    
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    
    /// <summary>
    /// SysRole
    /// </summary>
    public partial class SysRole:EntityBase
    {
        /// <summary>
        /// 编号
        /// </summary>
    	[Display(Name="编号")][Key]
        public string Id { get; set; }
    	   
        
        /// <summary>
        /// 名称
        /// </summary>
    	[Display(Name="名称")]
        public string Name { get; set; }
    	   
        
        /// <summary>
        /// 描述
        /// </summary>
    	[Display(Name="描述")]
        public string Description { get; set; }
    	   
        
        /// <summary>
        /// 创建时间
        /// </summary>
    	[Display(Name="创建时间")]
        public System.DateTime CreateTime { get; set; }
    	   
        
        /// <summary>
        /// 创建人
        /// </summary>
    	[Display(Name="创建人")]
        public string CreateUser { get; set; }
    	   
        
    }
}
