//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMS.Models
{
    
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    
    /// <summary>
    /// SysRole
    /// </summary>
    public partial class SysRole:EntityBase
    {
        /// <summary>
        /// Id
        /// </summary>
    	[Display(Name="Id")][Key]
        public string Id { get; set; }
    	   
        
        /// <summary>
        /// Name
        /// </summary>
    	[Display(Name="Name")]
        public string Name { get; set; }
    	   
        
        /// <summary>
        /// Description
        /// </summary>
    	[Display(Name="Description")]
        public string Description { get; set; }
    	   
        
        /// <summary>
        /// CreateTime
        /// </summary>
    	[Display(Name="CreateTime")]
        public System.DateTime CreateTime { get; set; }
    	   
        
        /// <summary>
        /// CreateUser
        /// </summary>
    	[Display(Name="CreateUser")]
        public string CreateUser { get; set; }
    	   
        
    }
}
