//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMS.Models
{
    
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    
    /// <summary>
    /// SysRight
    /// </summary>
    public partial class SysRight:EntityBase
    {
        /// <summary>
        /// Id
        /// </summary>
    	[Display(Name="Id")][Key]
        public string Id { get; set; }
    	   
        
        /// <summary>
        /// RoleId
        /// </summary>
    	[Display(Name="RoleId")]
        public string RoleId { get; set; }
    	   
        
        /// <summary>
        /// ModuleId
        /// </summary>
    	[Display(Name="ModuleId")]
        public string ModuleId { get; set; }
    	   
        
        /// <summary>
        /// Rightflag
        /// </summary>
    	[Display(Name="Rightflag")]
        public bool Rightflag { get; set; }
    	   
        
    }
}
