//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMS.Models
{
    
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    
    /// <summary>
    /// SysUser
    /// </summary>
    public partial class SysUser:EntityBase
    {
        /// <summary>
        /// Id
        /// </summary>
    	[Display(Name="Id")][Key]
        public string Id { get; set; }
    	   
        
        /// <summary>
        /// UserName
        /// </summary>
    	[Display(Name="UserName")]
        public string UserName { get; set; }
    	   
        
        /// <summary>
        /// Password
        /// </summary>
    	[Display(Name="Password")]
        public string Password { get; set; }
    	   
        
        /// <summary>
        /// TrueName
        /// </summary>
    	[Display(Name="TrueName")]
        public string TrueName { get; set; }
    	   
        
        /// <summary>
        /// Cards
        /// </summary>
    	[Display(Name="Cards")]
        public string Cards { get; set; }
    	   
        
        /// <summary>
        /// MobileNumber
        /// </summary>
    	[Display(Name="MobileNumber")]
        public string MobileNumber { get; set; }
    	   
        
        /// <summary>
        /// PhoneNumber
        /// </summary>
    	[Display(Name="PhoneNumber")]
        public string PhoneNumber { get; set; }
    	   
        
        /// <summary>
        /// QQ
        /// </summary>
    	[Display(Name="QQ")]
        public string QQ { get; set; }
    	   
        
        /// <summary>
        /// EmailAddress
        /// </summary>
    	[Display(Name="EmailAddress")]
        public string EmailAddress { get; set; }
    	   
        
        /// <summary>
        /// OtherContact
        /// </summary>
    	[Display(Name="OtherContact")]
        public string OtherContact { get; set; }
    	   
        
        /// <summary>
        /// Province
        /// </summary>
    	[Display(Name="Province")]
        public string Province { get; set; }
    	   
        
        /// <summary>
        /// City
        /// </summary>
    	[Display(Name="City")]
        public string City { get; set; }
    	   
        
        /// <summary>
        /// Village
        /// </summary>
    	[Display(Name="Village")]
        public string Village { get; set; }
    	   
        
        /// <summary>
        /// Address
        /// </summary>
    	[Display(Name="Address")]
        public string Address { get; set; }
    	   
        
        /// <summary>
        /// State
        /// </summary>
    	[Display(Name="State")]
        public Nullable<bool> State { get; set; }
    	   
        
        /// <summary>
        /// CreateTime
        /// </summary>
    	[Display(Name="CreateTime")]
        public Nullable<System.DateTime> CreateTime { get; set; }
    	   
        
        /// <summary>
        /// CreateUser
        /// </summary>
    	[Display(Name="CreateUser")]
        public string CreateUser { get; set; }
    	   
        
        /// <summary>
        /// Sex
        /// </summary>
    	[Display(Name="Sex")]
        public string Sex { get; set; }
    	   
        
        /// <summary>
        /// Birthday
        /// </summary>
    	[Display(Name="Birthday")]
        public Nullable<System.DateTime> Birthday { get; set; }
    	   
        
        /// <summary>
        /// JoinDate
        /// </summary>
    	[Display(Name="JoinDate")]
        public Nullable<System.DateTime> JoinDate { get; set; }
    	   
        
        /// <summary>
        /// Marital
        /// </summary>
    	[Display(Name="Marital")]
        public string Marital { get; set; }
    	   
        
        /// <summary>
        /// Political
        /// </summary>
    	[Display(Name="Political")]
        public string Political { get; set; }
    	   
        
        /// <summary>
        /// Nationality
        /// </summary>
    	[Display(Name="Nationality")]
        public string Nationality { get; set; }
    	   
        
        /// <summary>
        /// Native
        /// </summary>
    	[Display(Name="Native")]
        public string Native { get; set; }
    	   
        
        /// <summary>
        /// School
        /// </summary>
    	[Display(Name="School")]
        public string School { get; set; }
    	   
        
        /// <summary>
        /// Professional
        /// </summary>
    	[Display(Name="Professional")]
        public string Professional { get; set; }
    	   
        
        /// <summary>
        /// Degree
        /// </summary>
    	[Display(Name="Degree")]
        public string Degree { get; set; }
    	   
        
        /// <summary>
        /// Expertise
        /// </summary>
    	[Display(Name="Expertise")]
        public string Expertise { get; set; }
    	   
        
        /// <summary>
        /// JobState
        /// </summary>
    	[Display(Name="JobState")]
        public string JobState { get; set; }
    	   
        
        /// <summary>
        /// Photo
        /// </summary>
    	[Display(Name="Photo")]
        public string Photo { get; set; }
    	   
        
        /// <summary>
        /// Attach
        /// </summary>
    	[Display(Name="Attach")]
        public string Attach { get; set; }
    	   
        
    }
}
