//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMS.Models
{
    
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    
    /// <summary>
    /// SysUser
    /// </summary>
    public partial class SysUser:EntityBase
    {
        /// <summary>
        /// 编码
        /// </summary>
    	[Display(Name="编码")][Key]
        public string Id { get; set; }
    	   
        
        /// <summary>
        /// 密码
        /// </summary>
    	[Display(Name="密码")]
        public string Password { get; set; }
    	   
        
        /// <summary>
        /// 姓名
        /// </summary>
    	[Display(Name="姓名")]
        public string TrueName { get; set; }
    	   
        
        /// <summary>
        /// 移动电话
        /// </summary>
    	[Display(Name="移动电话")]
        public string MobileNumber { get; set; }
    	   
        
        /// <summary>
        /// 联系电话
        /// </summary>
    	[Display(Name="联系电话")]
        public string PhoneNumber { get; set; }
    	   
        
        /// <summary>
        /// QQ
        /// </summary>
    	[Display(Name="QQ")]
        public string QQ { get; set; }
    	   
        
        /// <summary>
        /// 邮件
        /// </summary>
    	[Display(Name="邮件")]
        public string EmailAddress { get; set; }
    	   
        
        /// <summary>
        /// 其他方式
        /// </summary>
    	[Display(Name="其他方式")]
        public string OtherContact { get; set; }
    	   
        
        /// <summary>
        /// 省
        /// </summary>
    	[Display(Name="省")]
        public string Province { get; set; }
    	   
        
        /// <summary>
        /// 市
        /// </summary>
    	[Display(Name="市")]
        public string City { get; set; }
    	   
        
        /// <summary>
        /// 县
        /// </summary>
    	[Display(Name="县")]
        public string Village { get; set; }
    	   
        
        /// <summary>
        /// 地址
        /// </summary>
    	[Display(Name="地址")]
        public string Address { get; set; }
    	   
        
        /// <summary>
        /// 启用
        /// </summary>
    	[Display(Name="启用")]
        public Nullable<bool> State { get; set; }
    	   
        
        /// <summary>
        /// 创建时间
        /// </summary>
    	[Display(Name="创建时间")]
        public Nullable<System.DateTime> CreateTime { get; set; }
    	   
        
        /// <summary>
        /// 创建人
        /// </summary>
    	[Display(Name="创建人")]
        public string CreateUser { get; set; }
    	   
        
        /// <summary>
        /// 性别
        /// </summary>
    	[Display(Name="性别")]
        public string Sex { get; set; }
    	   
        
        /// <summary>
        /// 出生日期
        /// </summary>
    	[Display(Name="出生日期")]
        public Nullable<System.DateTime> Birthday { get; set; }
    	   
        
        /// <summary>
        /// 注册日期
        /// </summary>
    	[Display(Name="注册日期")]
        public Nullable<System.DateTime> JoinDate { get; set; }
    	   
        
        /// <summary>
        /// 婚姻
        /// </summary>
    	[Display(Name="婚姻")]
        public string Marital { get; set; }
    	   
        
        /// <summary>
        /// 党派
        /// </summary>
    	[Display(Name="党派")]
        public string Political { get; set; }
    	   
        
        /// <summary>
        /// 民族
        /// </summary>
    	[Display(Name="民族")]
        public string Nationality { get; set; }
    	   
        
        /// <summary>
        /// 籍贯
        /// </summary>
    	[Display(Name="籍贯")]
        public string Native { get; set; }
    	   
        
        /// <summary>
        /// 毕业学校
        /// </summary>
    	[Display(Name="毕业学校")]
        public string School { get; set; }
    	   
        
        /// <summary>
        /// 就读专业
        /// </summary>
    	[Display(Name="就读专业")]
        public string Professional { get; set; }
    	   
        
        /// <summary>
        /// 学历
        /// </summary>
    	[Display(Name="学历")]
        public string Degree { get; set; }
    	   
        
        /// <summary>
        /// 个人简介
        /// </summary>
    	[Display(Name="个人简介")]
        public string Expertise { get; set; }
    	   
        
        /// <summary>
        /// 在职状况
        /// </summary>
    	[Display(Name="在职状况")]
        public string JobState { get; set; }
    	   
        
        /// <summary>
        /// 照片
        /// </summary>
    	[Display(Name="照片")]
        public string Photo { get; set; }
    	   
        
        /// <summary>
        /// 附件
        /// </summary>
    	[Display(Name="附件")]
        public string Attach { get; set; }
    	   
        
        /// <summary>
        /// 身份证
        /// </summary>
    	[Display(Name="身份证")]
        public string IdCards { get; set; }
    	   
        
    }
}
