//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMS.Models
{
    
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    
    /// <summary>
    /// SysUserRole
    /// </summary>
    public partial class SysUserRole:EntityBase
    {
        /// <summary>
        /// Id
        /// </summary>
    	[Display(Name="Id")][Key]
        public System.Guid Id { get; set; }
    	   
        
        /// <summary>
        /// SysUserId
        /// </summary>
    	[Display(Name="SysUserId")]
        public string SysUserId { get; set; }
    	   
        
        /// <summary>
        /// SysRoleId
        /// </summary>
    	[Display(Name="SysRoleId")]
        public string SysRoleId { get; set; }
    	   
        
    }
}
